# Generated by Django 5.0.7 on 2024-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0007_alter_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Super Admin', 'Super Admin')], max_length=50),
        ),
    ]
