# Generated by Django 5.0.7 on 2024-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0008_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
