# Generated by Django 5.0.7 on 2024-07-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('mrp', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('Amount', 'Amount'), ('Percentage', 'Percentage')], default='Amount', max_length=255)),
                ('discount_amount', models.FloatField()),
                ('sr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mfg_date', models.DateTimeField()),
                ('uom', models.CharField(max_length=255)),
                ('ptr', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('quantity_inwarded', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], default='In Stock', max_length=255)),
                ('inward_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Return', 'Return'), ('Replacement', 'Replacement'), ('Warehouse Transfer', 'Warehouse Transfer')], default='Purchase', max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('additional_details', models.JSONField()),
                ('status', models.CharField(choices=[('Inward', 'Inward'), ('Outward', 'Outward'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Expired', 'Expired'), ('Returned', 'Returned'), ('Adjusment', 'Adjustment'), ('Warehouse Transfer', 'Warehouse Transfer')], default='Inward', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackAndShelvesAndFloors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rack', models.CharField(blank=True, max_length=255, null=True)),
                ('shelf', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deleted', 'Deleted')], default='Active', max_length=255)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=255)),
                ('capacity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=255)),
                ('warehouse_type', models.CharField(choices=[('Owned', 'Owned'), ('Leased', 'Leased')], default='Owned', max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
