# Generated by Django 5.0.7 on 2024-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
